name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate package.json
        uses: ExpediaGroup/package-json-validator@v1
        with:
          rules: ranges
          dependency-types: dependencies

      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Run Lint
        run: bun lint

      - name: Build
        run: bun run build
